### PR TITLE
Testing branch

### PR DESCRIPTION
**Pull request by mueni-eng**
Added question constructor and 1 test for initializing the object

### CODE REVIEW

**Review by markgoertz — COMMENTED** [review]
The reason for the conflicts are older versions of the dependencies that are in main, so resolve these first and then make a PR👍

**Review by Luca-Bulles — CHANGES_REQUESTED** [review]
Folder name type -> IntergartionTests. this needs to be changed to IntegrationTests. Rename this and create new PR to merge to main. 

inside this file are comment statements that are empty (don't contain methods that belong to the comment)
backend/BackendAnswerTests/IntergartionTests/AnswerControllerTests.cs

After these 2 small changes it should be fine

**Comment by markgoertz** [comment]
There are still conflicts😅

**Comment by Luca-Bulles** [comment]
There are conflicts that keep you from merging into main, please solve these before creating a new Pull request

**Pull request closed without merging**
